name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Generate platform folders
        working-directory: mobile
        run: flutter create --org com.hesabyar --project-name hesabyar_tanakhah .
      - name: Get packages
        working-directory: mobile
        run: flutter pub get
      - name: Build APK
        working-directory: mobile
        run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
