name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Generate platform folders
        working-directory: mobile
        run: flutter create --org com.hesabyar --project-name hesabyar_tanakhah .
      - name: Disable Impeller rendering workaround
        working-directory: mobile
        run: |
          sed -i 's#</application>#    <meta-data android:name="io.flutter.embedding.android.EnableImpeller" android:value="false" />\n</application>#' android/app/src/main/AndroidManifest.xml
      - name: Update Kotlin version
        working-directory: mobile
        run: |
          sed -i 's/id "org.jetbrains.kotlin.android" version "[^"]*"/id "org.jetbrains.kotlin.android" version "1.9.22"/' android/settings.gradle
      - name: Get packages
        working-directory: mobile
        run: flutter pub get
      - name: Build APK
        working-directory: mobile
        run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
